name: HeartEffect
version: '${project.version}'
main: hakasenz.herteffect.HeartEffect
api-version: 1.20
commands:
  hearteffect:
    description: Reloads the plugin configuration
    permission: hearteffect.reload
    usage: /hearteffect