name: HeartEffect
version: '1.0-SNAPSHOT'
main: hakasenz.herteffect.HeartEffect
api-version: 1.20
commands:
  hearteffect:
    description: Reloads the plugin configuration
    permission: hearteffect.reload
    usage: /hearteffect